"""
Django settings for WebAgro project.

Generated by 'django-admin startproject' using Django 2.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATIC_ROOT = os.path.join(BASE_DIR,'static')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '2zrp%95jv4oatb6*(6-p+ov_u+25*$39_$qv=uc^dak836rr()'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'admin_view_permission',
    'admin_reorder',
    'Agronomy.apps.AgronomyConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'smart_selects',

]

MIDDLEWARE = [
    'admin_reorder.middleware.ModelAdminReorder',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]



ADMIN_REORDER = (
    # Keep original label and models
    'sites',

    {'app': 'Agronomy', 'label': 'Agronomy Table', 'models': ('Agronomy.Crop', 'Agronomy.Crop_Varieties',
     'Agronomy.variety_growth_stage', 'Agronomy.reco_Category', 'Agronomy.tbl_ag_growth_stage_recos', 'Agronomy.affliation_mask'
    , 'Agronomy.growth_stage_pests_alerts_recos'
    , 'Agronomy.growth_stage_weeds_alerts_recos'
    , 'Agronomy.country_table',)},


    {'app': 'Agronomy', 'label': 'Agronomy Flags', 'models': ('Agronomy.growth_stage_recos_variety_flags',  'Agronomy.growth_stage_abiotic_stresses_alerts_recos',
                                                                    'Agronomy.growth_stage_abiotic_stresses_alerts_variety_flags',
                                                                     'Agronomy.growth_stage_pests_alerts_variety_flags'
                                                                    , 'Agronomy.growth_stage_weeds_alerts_variety_flags',
                                                                      'Agronomy.agro_input_product_branded_list',)},


    {'app': 'Agronomy', 'models': ('Agronomy.User', )},


    {'app': 'Agronomy', 'label': 'Agronomy Lists', 'models': ('Agronomy.Crop_growth_stage_lists',
                                                               'Agronomy.stress_type_list',
                                                              'Agronomy.stress_list',  'Agronomy.product_type_list',
                                                              'Agronomy.agro_input_product_list'
                                                               'Agronomy.brand_list', 'Agronomy.country_region_list',
                                                              )},


    {'app': 'auth', 'models': (
        'auth.Group',
        {'model': 'auth.User', 'label': 'Staff'},
    )},

)



ROOT_URLCONF = 'WebAgro.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'WebAgro.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'Agronomy',
        'USER': 'postgres',
        'PASSWORD': 'Lemon',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'

USE_DJANGO_JQUERY = True
